Add file extension info to the system prompt
yacineMTB/dingllm.nvim pull request #4
Opened 2024-07-27 13:17 UTC by nilszeilon

Added file extension info to the system prompt, sometimes it would give me code in another language than the intended if that information was missing.

2024-08-04 02:23 UTC, yacineMTB requested changes
Thanks for this, this is a great idea.
Do you think we could instead add a function that constructs the system prompt? So that we can change the function in config to programatically construct system prompts based on runtime context

2024-08-04 18:42 UTC, nilszeilon commented
I agree, that is cleaner. Now your system prompt can be passed through the function 'create_prompt' which replaces $file_ext variable in the system prompt with the actual file extension.

2024-08-09 16:21 UTC, adharm commented
Would it would be more extensible/easier to update by putting the constructor in the config? Then dingllm.lua wouldn't have to change every time you wanted to add more context. So something like:
```
return {
...
    local helpful_prompt = 'You are a helpful assistant. What I have sent are my notes so far. You are very curt, yet helpful.'

    local function construct_replace_prompt()
      local base_replace_prompt =
        'You should replace the code that you are sent, only following the comments. Do not talk at all. Only output valid code. 
         Do not provide any backticks that surround the code. Never ever output backticks like this ```. Any comment that is 
         asking you for something should be removed after you satisfy them. Other comments should left alone. Do not output 
          backticks.'
      -- append file extension to prompt
      local file_ext = vim.bo.filetype
      local replace_prompt = base_replace_prompt .. ' Note that this is a ' .. file_ext .. ' file.'
      -- add other prompt additions as needed
      return replace_prompt
    end

    local function groq_replace()
      dingllm.invoke_llm_and_stream_into_editor({
        url = 'https://api.groq.com/openai/v1/chat/completions',
        model = 'llama-3.1-70b-versatile',
        api_key_name = 'GROQ_API_KEY',
        system_prompt = construct_replace_prompt(),
        replace = true,
      }, dingllm.make_openai_spec_curl_args, dingllm.handle_openai_spec_data)
    end

    local function groq_help()
      dingllm.invoke_llm_and_stream_into_editor({
        url = 'https://api.groq.com/openai/v1/chat/completions',
        model = 'llama-3.1-70b-versatile',
        api_key_name = 'GROQ_API_KEY',
        system_prompt = helpful_prompt,
        replace = false,
      }, dingllm.make_openai_spec_curl_args, dingllm.handle_openai_spec_data)
    end
 ...
 }
```

2024-08-13 23:41 UTC, yacineMTB requested changes

2024-08-13 23:41 UTC, yacineMTB commented on lua/dingllm.lua
> +
Sorry for the back and forth and also lag. But I meant actually make system prompt a variable that can be either a function or string. If it's a function, take whatever it returns. If it's a string, use as is. If that makes sense!

2024-09-13 22:13 UTC, closed without merging